name: On Tag, Build and Push PERN Docker Images to GHCR

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Required to push images to GHCR

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Convert repository owner to lowercase (docker image names must all be lowercase)
      - name: Set repository owner lowercase
        id: owner_lowercase
        run: echo "owner_lowercase=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # Step 4: Build the React app
      - name: Install and Build React App
        run: |
          cd react/pern-todo-app
          npm ci # Install dependencies (prefer ci for CI environments)
          npm run build # Build the React app
          cd ../../ # Return to home directory

      # Step 5: Get the tag associated with push for the react image
      - name: Extract metadata for React Docker image
        id: react_meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.owner_lowercase }}/pern-react-todo
          tags: |
            type=ref,event=tag

      # Step 6: Build and Push React Docker Image
      - name: Build and Push React App Image
        uses: docker/build-push-action@v5
        with:
          context: react/pern-todo-app
          push: true
          tags: ${{ steps.react_meta.outputs.tags }}

      # Step 7: Get the tag associated with push for the express image
      - name: Extract metadata for Express Docker image
        id: express_meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.owner_lowercase }}/pern-express-todo
          tags: |
            type=ref,event=tag

      # Step 8: Build and Push Express Docker Image
      - name: Build and Push Express App Image
        uses: docker/build-push-action@v5
        with:
          context: express
          push: true
          tags: ${{ steps.express_meta.outputs.tags }}

      # Step 9: Get the tag associated with push for the postgres image
      - name: Extract metadata for Postgres Docker image
        id: postgres_meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.owner_lowercase }}/pern-postgres-todo
          tags: |
            type=ref,event=tag

      # Step 10: Build and Push Postgres Docker Image
      - name: Build and Push Postgres Image
        uses: docker/build-push-action@v5
        with:
          context: postgres
          push: true
          tags: ${{ steps.postgres_meta.outputs.tags }}
